### ISSUE TITLE
结束不了回答

### ISSUE THREAD

**Issue by fangkangwei** [phoooob/chatgpt-office#1]
![image](https://github.com/phoooob/chatgpt-office/assets/132995270/25842d32-f47e-44a1-ab99-8ff36a67d35f)

**Comment by phoooob** [comment]
飞书有最长3s响应时间的限制，服务器响应超过3s就会报错，理论上只要服务器的逻辑还在继续执行，就不影响结束。

**Comment by BigHeadShang** [comment]
我也遇到了这个问题

**Comment by phoooob** [comment]
> 我也遇到了这个问题

在飞书开放平台 > 机器人菜单 > 机器人配置 > 消息卡片请求网址 中，确认是否已配置回调地址。

![image](https://github.com/phoooob/chatgpt-office/assets/13043634/ed7dbffa-a9d9-4d25-b0b5-e7ed045e6b28)
