### ISSUE TITLE
单次会话中，上下文关联的能力很差

### ISSUE THREAD

**Issue by qingmei2** [phoooob/chatgpt-office#2]
参考下图，可以清晰的看到，连续问答中，上下文关联能力较差（模型 3.5-turbo)

![image](https://github.com/phoooob/chatgpt-office/assets/21142152/a6b89d00-0881-47df-8052-c0947362a4a2)

但在官方的 Web 端或者 IDE 插件中，效果良好：

![image](https://github.com/phoooob/chatgpt-office/assets/21142152/eaa580ce-93ef-4f3d-bbd6-6e972d491083)

请问这个是需要什么参数来解决吗，还是官方公开的API集成文档中，并未提供类似能力？

**Comment by phoooob** [comment]
![image](https://github.com/phoooob/chatgpt-office/assets/13043634/cb7a625d-f39d-4059-a81d-896997bbf7e3)

实测效果貌似是因人而异的，每一次的回答存在不确定性。
上下文关联能力的原理是每次提问题都携带上之前的问题与答案作为参数，所以不存在官方与API的差异。
